### ISSUE TITLE
starting up mintty doesn't load profile

### ISSUE THREAD

**Issue by dcoli** [karlin/mintty-colors-solarized#1]
Hi,

Thanks for this port!

I tried adding it to the bottom of my .bashrc file, but it's not loading it. But when I execute ./.bashrc, it sort of loads it - that is, the shell shows the pale yellow text on a dark green background, but no other colors for directories, etc. Emacs, however, looks sharp and syntax sensitive.

Any ideas?

**Comment by karlin** [comment]
dcoli,

This could be related to other lines in your `.bashrc`. Is it possible that you aren't using `ls --color`? You could try running the script at http://gist.github.com/813124 and compare to the Solarized homepage to debug.

**Comment by dcoli** [comment]
adding bash to the mintty command (I think it was 'mintty.exe -bash', but i forget) allowed bash to be set as the default shell. this then properly loaded the bashrc, which brought in the solarized colors. thanks!
