### ISSUE TITLE
Solarized bold colors are gray -- is the theme buggy?

### ISSUE THREAD

**Issue by fniessen** [karlin/mintty-colors-solarized#4]
Dear, IIUC (!), MinTTY's team would say that this theme is buggy?
See https://github.com/mintty/mintty/issues/683.

WDYT?

What's the problem?  And the solution??

**Comment by karlin** [comment]
Yes, this theme is "buggy" in the same sense as other terminal adaptations of Solarized. I've used the suggested mapping for terminal colors from the author. For example, I'm using the same mapping as [the OS X Terminal version included in the author's repo](https://github.com/altercation/ethanschoonover.com/tree/master/projects/solarized/osx-terminal.app-colors-solarized).

It doesn't map the expected terminal colors in all cases. Take "Bold Green" for example:

    base01    #586e75 10/7 brgreen  240 #585858 45 -07 -07  88 110 117 194  25  46

As seen in the Solarized example, "base01" is a very gray "content tone":

![Solarized palette](https://raw.githubusercontent.com/altercation/solarized/master/img/solarized-palette.png)
